7 cpp20
MikhailBerezhanov/SimpleDimple pull request #15
Opened 2024-07-10 18:35 UTC by MikhailBerezhanov

Added new docker container to enable C++20 standard

2024-07-10 20:16 UTC, Drone29 requested changes
commented the sections that need attention

2024-07-11 08:36 UTC, MikhailBerezhanov commented on builder/Dockerfile
> +    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
yep, will add

2024-07-11 08:47 UTC, Drone29 commented
add ```DOWNLOAD_EXTRACT_TIMESTAMP FALSE``` to FetchContent_Declare in test/utest/CMakeLists.txt to suppress warning:
```
FetchContent_Declare(
    googletest
    URL "https://github.com/google/googletest/archive/refs/tags/v1.14.0.zip"
    DOWNLOAD_EXTRACT_TIMESTAMP FALSE # suppress warning
)
```

2024-07-11 15:25 UTC, Drone29 approved these changes

2024-07-11 15:25 UTC, merged