logger added
MikhailBerezhanov/SimpleDimple pull request #17
Opened 2024-07-11 16:50 UTC by MikhailBerezhanov

2024-07-11 17:05 UTC, MikhailBerezhanov commented
Main usage is :

```C
LOG_F_DEBUG(message) 
LOG_F_INFO(message) 
LOG_F_WARNING(message) 
LOG_F_ERROR(message) 
```

Output format example:

```
0711-16:39:48.599 7F5C69FB6000 D Starting ./Linux/test_game
0711-16:39:48.621 7F5C69FB6000 I Log finished.
```

Usage with classes:

```C
class MyCLass : private Logable
{
    MyCLass() : Logable("MyClassName") {}
}
```

That will create prefix logger with `MyClassName` tag before any message from this class .

2024-07-12 09:38 UTC, Drone29 requested changes
see comments on the parts needing attention

2024-07-12 09:50 UTC, MikhailBerezhanov commented on src/main.cpp
> +    const LoggerInitializer loggerInitialer(LogLevel::Debug);
This is just an example of usage

2024-07-12 09:52 UTC, MikhailBerezhanov commented on src/logger.h
> +#define LOG_DEBUG(message) GetLogger()->Log(GameEngine::LogLevel::Debug, message)
Another level of error-handling with  _func_  will be added in next review .

2024-07-14 14:33 UTC, closed without merging

2024-07-14 14:33 UTC, MikhailBerezhanov commented
Rebase was needed -> opened new branch