Window and Texture classes with interfaces
MikhailBerezhanov/SimpleDimple pull request #18
Opened 2024-07-12 10:05 UTC by Drone29

Window abilities:
Create, resize, move, show/hide, draw points, lines,etc; 
Add/remove textures to/from window, activate/deactivate textures

Texture:
Create from image, move, rotate, resize, flip

Closes #9

2024-07-12 12:06 UTC, Drone29 commented
UPD: renamed files, added intermediate proxy class to Texture

2024-07-13 06:52 UTC, MikhailBerezhanov requested changes
Please fix the comments

2024-07-13 06:52 UTC, MikhailBerezhanov commented on src/Texture.cpp
> +    SDL_Texture *Texture::get_texture() const {
Is It typo , or you suggest to have private methods in different styling ? 
It's not bad idea, but lets be consistent and have camelCase - private method can start from `lowercase` or with `_` for example .

`get_texture` ->  `getTexture`    or  `_GetTexture()`

2024-07-13 06:52 UTC, MikhailBerezhanov commented on src/Texture.h
> +        // intermediate class to isolate SDL properties from Window's direct access
But there are `get_texture()` and other methods, that gives direct access . Not sure that comment is actual

2024-07-13 06:52 UTC, MikhailBerezhanov commented on src/Texture.h
> +        void SetPixelData(const std::vector<uint8_t> &pixel_data) const override;
`pixelData`.  And there are also some special format depending on texture should be supported as I can see from SDL doc .  Should we add some checks or expects ?

2024-07-13 06:52 UTC, MikhailBerezhanov commented on src/Texture.cpp
> +    void Texture::SetPixelData(const std::vector<uint8_t> &pixel_data) const {
There are some requirements about `pixelData` that should be checked I think : 

https://wiki.libsdl.org/SDL2/SDL_UpdateTexture#remarks

2024-07-13 06:52 UTC, MikhailBerezhanov commented on src/Window.cpp
> +        SDL_RenderClear(m_renderer);
`EXPECT`

function has return code:

https://wiki.libsdl.org/SDL2/SDL_RenderClear

And also method name supposed to clear window's content, but here we are clearing Renderer buffer if I'm not mistaken. 
Probably it should be as :

```C
  SDL_RenderClear()
  SDL_RenderPresent ()
  ```
  (?) 
  to make blank window .
  
  Or name of method must be changed

2024-07-13 06:52 UTC, MikhailBerezhanov commented on src/IWindow.h
> +        /// Window actions
Not sure that window actions must be strictly `const` methods in interface. In common case it can change state I think . 

Show()
Hide()
Raise()
Maximize
Minimize
Restore
Clear
Refresh
Present

Making them const in interface we block the apportunity of state changes. **But** can be fixed later , when we'll met the case .

2024-07-13 06:52 UTC, MikhailBerezhanov commented on src/Window.h
> +        Size2D get_size_generic(void (*sdl_func)(SDL_Window *, int *, int *)) const;
`getSizeGeneric`  or `_GetSizeGeneric`  should be more consisnte.  And all aother get_smth_funcutoins the same

2024-07-13 06:52 UTC, MikhailBerezhanov commented on src/Window.cpp
> +        EXPECT(it != m_textures.end(), "Texture not found");
"Texture not found"   ->  `"Texture " + texture_id + " not found"`

2024-07-13 06:52 UTC, MikhailBerezhanov commented on src/Window.cpp
> +        return *m_textures.at(texture_id);
Should also add check if texture_id is in container . Otherwise we will face with common exception description lke `at() throws` with now information

2024-07-13 06:52 UTC, MikhailBerezhanov commented on src/Window.cpp
> +    size_t Window::AppendTexture(const Size2D &size) {
Can Textures be Appended from different threads ?

2024-07-13 06:52 UTC, MikhailBerezhanov commented on src/Window.cpp
> +    void Window::Refresh() const {
`SDL_RenderClear()`  should also be called before each frame drawing

https://wiki.libsdl.org/SDL2/SDL_RenderPresent

2024-07-13 08:22 UTC, Drone29 commented on src/IWindow.h
> +        virtual IWindow & SetAlwaysOnTop(bool on_top) = 0;
SetOnTop() / IsOnTop() ?

IsOnTop sounds like getter

2024-07-13 08:27 UTC, Drone29 commented on src/Window.h
> +        Size2D get_size_generic(void (*sdl_func)(SDL_Window *, int *, int *)) const;
I used snake_case here to indicate that it's a private function

2024-07-13 08:31 UTC, Drone29 commented on src/Window.cpp
> +    size_t Window::AppendTexture(const Size2D &size) {
Could be, who knows. I wouldn't bother with threads right now, better keep things simple

2024-07-13 08:32 UTC, Drone29 commented on src/Window.cpp
> +    void Window::Refresh() const {
That's what Window::Clear() does

2024-07-13 09:22 UTC, Drone29 reviewed
applied some changes

2024-07-13 09:22 UTC, Drone29 commented on src/Texture.h
> +        // intermediate class to isolate SDL properties from Window's direct access
It doesn't give direct access, it exposes properties throw methods
i.e. you can't do `texture.m_angle = 123.6` from Window and that was the whole idea
And some of these methods are const

2024-07-13 09:22 UTC, Drone29 commented on src/Texture.h
> +            SDL_Texture *m_texture;
What do we achieve with unique_ptr ?
And to declare it we'd need to do that: 
`std::unique_ptr<SDL_Texture, decltype(SDL_DestroyTexture)> m_texture;`
which looks far less readable than it is now

2024-07-13 09:22 UTC, Drone29 commented on src/Texture.h
> +        void SetPixelData(const std::vector<uint8_t> &pixel_data) const override;
format is default and is set in the Texture constructor for now
I can check vector's size divisibility by 4 and throw if it's not, but that's as good as gets for now
I'm not even sure we need that function at all

2024-07-13 09:22 UTC, Drone29 commented on src/Window.cpp
> +        SDL_RenderClear(m_renderer);
SDL_RenderPresent() presents content, not clearing it
single SDL_RenderClear() is enough to clear the screen
it's SDL_RenderCopy() who determines what to show on the next SDL_RenderPresent() call

2024-07-13 09:22 UTC, Drone29 commented on src/Window.h
> +        SDL_Window *m_window;
what do we achieve with them?

2024-07-13 10:14 UTC, MikhailBerezhanov approved these changes

2024-07-13 10:14 UTC, merged