Introducing GameObject and Components
MikhailBerezhanov/SimpleDimple pull request #32
Opened 2024-07-23 13:55 UTC by Drone29

Now we have a GameObject class that can hold zero or more Components
Components are (for now):
- Transform (responsible for coordinates, size, rotation, etc)
- Renderer (responsible for rendering textures and graphical primitives to the screen)
- Texture (holds properties of a texture like color, alpha, pixel data)

2024-07-24 16:09 UTC, MikhailBerezhanov requested changes
Please fix comments

2024-07-24 16:09 UTC, MikhailBerezhanov commented on src/GameObject.h
> +        std::map<GameObjectComponentType, ComponentPtr> m_components;
`std::vector` with GameObjectComponentType as index ?

2024-07-24 17:59 UTC, Drone29 commented on src/TextureComponent.h
> +        TextureComponent& operator=(const TextureComponent&) = delete;
Move ctor and operator= are not generated since their copy counterparts are explicitly deleted.

2024-07-24 18:01 UTC, Drone29 commented on src/TransformComponent.h
> +        TransformComponent &operator=(const TransformComponent &) = delete;
Not generated and until we need it to be movable better to leave it this way

2024-07-24 18:03 UTC, Drone29 commented on src/TransformComponent.cpp
> +        m_rect.w = static_cast<int>(size.w);
w/h cannot be negative and size_t ensures they're not

2024-07-24 18:04 UTC, Drone29 commented on src/TransformComponent.cpp
> +        int fac = static_cast<int>(factor);
Factor cannot be negative

2024-07-24 18:05 UTC, Drone29 commented on src/TransformComponent.cpp
> +    void TransformComponent::Downscale(unsigned int factor) {
Factor cannot be negative

2024-07-24 18:07 UTC, Drone29 commented on src/Types.h
> +#define _GOC_TYPES_ \
GameObjectComponent
That define never leaves this file, so there's no reason to give it a long name.
Though some comments might be useful

2024-07-24 18:08 UTC, Drone29 commented on src/Types.h
> +    class None{};
Used along with std::any to distinguish whether an argument is provided or not

2024-07-24 18:09 UTC, Drone29 commented on src/main.cpp
> +        auto renderer = std::dynamic_pointer_cast<RendererComponent>(go->GetComponent(GameObjectComponentType::RENDERER));
Otherwise it'd be 2 more lines to retrieve raw pointer with get() and then create a new smart ptr. Why not use std for that?

2024-07-24 19:07 UTC, Drone29 commented on src/TextureComponent.h
> +            friend class TextureComponent;
The point of `SDL_Handle` is to ensure nobody except TextureComponent can access `m_texture` directly.
If it was a struct, then `RendererComponent` and `GameObject` would be able to modify it like that:
`textureComponent.m_sdlHandle.m_texture = nullptr` or do some other nasty stuff, which we don't want

2024-07-24 19:15 UTC, Drone29 commented on src/TransformComponent.cpp
> +    void TransformComponent::Downscale(unsigned int factor) {
With `unsigned int` there's another layer of protection: if we try to pass a signed type to that method, we'll get a warning at compilation stage. With factor being an `int` we'll be left with runtime checks only

2024-07-24 19:23 UTC, Drone29 commented on src/GameObject.cpp
> +        return m_components.at(type);
.at() already handles non-existing keys by throwing `std::out_of_range` so there's no need for additional checks

2024-07-26 07:51 UTC, MikhailBerezhanov commented on src/Types.h
> +    class None{};
Ok

2024-07-26 13:04 UTC, MikhailBerezhanov requested changes

2024-07-26 13:04 UTC, MikhailBerezhanov commented on src/TransformComponent.cpp
> +        m_sdlHandle.m_flip = static_cast<SDL_RendererFlip>(m_sdlHandle.m_flip ^ SDL_FLIP_HORIZONTAL);
How about :

`m_sdlHandle.m_flip ^= SDL_FLIP_VERTICAL`
and 
`m_sdlHandle.m_flip ^= SDL_FLIP_HORIZONTAL`

?

2024-07-26 13:36 UTC, MikhailBerezhanov requested changes
Think of refactoring `RendererComponent::OnUpdate()` please.

2024-07-26 13:36 UTC, MikhailBerezhanov commented on src/RendererComponent.cpp
> +    RendererComponent::RendererComponent(const RenderContext &context, std::shared_ptr<const TransformComponent> transform)
Better to pass transform as `const ref` to avoid extra shared_ptr constructor

2024-07-26 13:36 UTC, MikhailBerezhanov commented on src/RendererComponent.cpp
> +    void RendererComponent::AddTexture(std::shared_ptr<TextureComponent> tex) {
const ref for tex

2024-07-26 13:36 UTC, MikhailBerezhanov commented on src/RendererComponent.cpp
> +            unsigned int tex_in_this_line;
= 0

2024-07-26 13:36 UTC, MikhailBerezhanov commented on src/RendererComponent.cpp
> +        while(! textures_q->empty()) {
Looks like can be refactored and made inside `m_textureHdl` with another method.
No need in `m_textureHdl.get_textures_queue();`  and external indexes  line_idx tex_in_line_idx ,

RendererComponent::OnUpdate()  should just take some textures and  render it.  Less logic should be more clear.

2024-07-26 13:38 UTC, MikhailBerezhanov commented on src/TransformComponent.cpp
> +        m_sdlHandle.m_flip = static_cast<SDL_RendererFlip>(m_sdlHandle.m_flip ^ SDL_FLIP_HORIZONTAL);
hmm ,  is `static_cast<SDL_RendererFlip>(int)` safe then ?

2024-07-26 13:41 UTC, MikhailBerezhanov commented on src/TransformComponent.cpp
> +        m_sdlHandle.m_flip = static_cast<SDL_RendererFlip>(m_sdlHandle.m_flip ^ SDL_FLIP_HORIZONTAL);
Suggest making it as 
```C
if (IsFlippedHorizontally)
{
   m_sdlHandle.m_flip &= ~SDL_FLIP_HORIZONTAL;
}
else
{
   m_sdlHandle.m_flip |= SDL_FLIP_HORIZONTAL
}
```

2024-07-27 05:51 UTC, MikhailBerezhanov approved these changes

2024-07-27 05:52 UTC, merged