InputEventPublisher + tests added
MikhailBerezhanov/SimpleDimple pull request #36
Opened 2024-07-25 17:32 UTC by MikhailBerezhanov

Introducing `InputEventPublisher` class

In next steps GameLoop class will be inherited from this class:

```C
class GameLoop : private InputEventPublisher
// making it IInputPublisher by inheritance chain

class GameObject : public IInputEvent
// override OnKey...() methods
```

2024-07-27 08:30 UTC, Drone29 requested changes
some changes and/or clarifications required, see comments

2024-07-27 08:30 UTC, Drone29 commented on src/InputEvent.h
> +        const std::unique_lock lock(m_mtx);
why unique_lock and not `scoped_lock`? There's no condition variables anywhere

2024-07-27 08:30 UTC, Drone29 commented on src/InputEvent.h
> +        const std::unique_lock lock(m_mtx);
`scoped_lock`?

2024-07-27 08:30 UTC, Drone29 commented on src/InputEvent.h
> +        const std::unique_lock lock(m_mtx);
`scoped_lock`?

2024-07-27 08:30 UTC, Drone29 commented on src/InputEvent.h
> +    void OnKeyPress(int keyCode) override
consider moving methods' implementation to a separate `.cpp` file

2024-07-27 08:30 UTC, Drone29 commented on test/utest/Mock.h
> +    struct InputEventMock : GameEngine::IInputEvent
why not declare it in `TestInputEvent.cpp`? It doesn't seem to be used anywhere else

2024-07-27 08:30 UTC, Drone29 commented on src/InputEvent.h
> +struct IInputEvent
shouldn't these structs be declared in separate `IInputEvent.h` `IInputEventPublisher.h` interface files?

2024-07-27 10:49 UTC, MikhailBerezhanov commented on test/utest/Mock.h
> +    struct InputEventMock : GameEngine::IInputEvent
this header file is supposed to contain all other mocks of our classes and be used thou other unit tests.

2024-07-27 10:51 UTC, MikhailBerezhanov commented on src/InputEvent.h
> +struct IInputEvent
I'll separate realization of InputEventPublisher , but think that will leave IInputEvent and IInputEventPublisher in one header because they are logically linked.

2024-07-28 06:35 UTC, MikhailBerezhanov commented on src/InputEvent.h
> +        const std::unique_lock lock(m_mtx);
mutex removed

2024-07-28 19:20 UTC, Drone29 approved these changes

2024-07-28 19:20 UTC, merged