Texture matrix
MikhailBerezhanov/SimpleDimple pull request #46
Opened 2024-08-05 12:17 UTC by Drone29

Introduces TextureMatrix component that holds a 2d array of textures
also some minor fixes and refactors

Closes #33

2024-08-08 06:09 UTC, MikhailBerezhanov requested changes

2024-08-08 06:09 UTC, MikhailBerezhanov commented on src/TextureMatrixComponent.cpp
> +        for(auto & row : rows) {
auto &&

2024-08-08 06:09 UTC, MikhailBerezhanov commented on src/TextureMatrixComponent.h
> +        std::vector<RowIdxLen> m_rowMap;
Why row**Map**  if it's vector?

2024-08-08 07:29 UTC, Drone29 commented on src/TextureMatrixComponent.h
> +        std::vector<RowIdxLen> m_rowMap;
it's a matrix represented by 1d vector with indexes instead of vector<vector>
that way it's more cache-friendly and there's an option to easily serialize that matrix by simply returning the ref to vector

2024-08-10 09:53 UTC, MikhailBerezhanov requested changes
Add unit tests for `TextureMatrixComponent` please .

2024-08-10 09:53 UTC, MikhailBerezhanov commented on src/TextureMatrixComponent.cpp
> +    TextureMatrixComponent::TextureMatrixComponent(std::vector<std::vector<TexturePtr>> &&rows) {
rows -> `matrix` rename ?

2024-08-10 09:53 UTC, MikhailBerezhanov commented on src/TextureMatrixComponent.cpp
> +        const auto &row = m_rowMap.at(row_idx);
row -> `rowIdxLen` ?

2024-08-10 09:53 UTC, MikhailBerezhanov commented on src/TextureMatrixComponent.h
> +        std::span<const TexturePtr> GetRow(size_t row) const;
row -> `rowIdx`

2024-08-10 09:53 UTC, MikhailBerezhanov commented on src/TextureMatrixComponent.h
> +        std::vector<RowIdxLen> m_rowMap;
Could use traditional matrix as `vector<vector<TexturePtr>>`, but ok .

2024-08-10 12:28 UTC, Drone29 commented
Updated with ComponentMatrix template and corresponding tests

2024-08-11 08:02 UTC, MikhailBerezhanov requested changes
Minor renaming in TestMatrix needed

2024-08-11 08:30 UTC, Drone29 commented
renamed

2024-08-11 08:48 UTC, MikhailBerezhanov approved these changes

2024-08-11 08:49 UTC, merged